import React from "react";
import {
  Terminal,
  History as HistoryIcon,
  X,
  HelpCircle,
  Lightbulb,
  Zap,
  CheckCircle2,
  AlertCircle,
  Loader2,
} from "lucide-react";

interface QueryResultsAreaProps {
  queryResults: Record<string, unknown>[] | Record<string, unknown> | null;
  bottomTab: "results" | "history";
  onSetTab: (tab: "results" | "history") => void;
  onClose: () => void;
  aiOutput: string | null;
  onCloseAiOutput: () => void;
  aiMode: string;
  isLoadingHistory: boolean;
  queryHistory: {
    id: string;
    query: string;
    success: boolean;
    executionTimeMs: number;
    createdAt: string;
  }[];
  isRunning?: boolean;
  onRestoreQuery: (query: string) => void;
}

const QueryResultsArea = ({
  queryResults,
  bottomTab,
  onSetTab,
  onClose,
  aiOutput,
  onCloseAiOutput,
  aiMode,
  isLoadingHistory,
  queryHistory,
  isRunning,
  onRestoreQuery,
}: QueryResultsAreaProps) => {
  if (!queryResults && bottomTab !== "history" && !isRunning) return null;

  // ... existing header logic ...

  return (
    <div className="flex-1 flex flex-col bg-[#021016]/50 overflow-hidden border-t border-white/5 min-h-0 animate-in slide-in-from-bottom duration-500">
      {/* Header omitted for brevity in targetContent, but I need to include it in replacementContent if I'm replacing the whole block */}
      <div className="flex items-center justify-between px-4 lg:px-6 py-2 border-b border-white/5 bg-black/20 shrink-0">
        <div className="flex items-center gap-4 lg:gap-6">
          <button
            onClick={() => onSetTab("results")}
            className={`flex items-center gap-2 lg:gap-3 py-1 transition-all relative ${bottomTab === "results" ? "text-white" : "text-zinc-500 hover:text-zinc-300"}`}
          >
            <Terminal className="h-3.5 w-3.5 text-white" />
            <span className="text-[10px] font-black uppercase tracking-widest whitespace-nowrap">
              Query Output
            </span>
            {bottomTab === "results" && (
              <div className="absolute -bottom-[9px] left-0 right-0 h-0.5 bg-primary shadow-[0_0_8px_rgba(0,237,100,0.5)]" />
            )}
          </button>
          <button
            onClick={() => onSetTab("history")}
            className={`flex items-center gap-2 lg:gap-3 py-1 transition-all relative ${bottomTab === "history" ? "text-white" : "text-zinc-500 hover:text-zinc-300"}`}
          >
            <HistoryIcon className="h-3.5 w-3.5 text-white" />
            <span className="text-[10px] font-black uppercase tracking-widest whitespace-nowrap">
              History
            </span>
            {bottomTab === "history" && (
              <div className="absolute -bottom-[9px] left-0 right-0 h-0.5 bg-primary shadow-[0_0_8px_rgba(0,237,100,0.5)]" />
            )}
          </button>
        </div>
        <button
          onClick={onClose}
          className="p-1 hover:text-white text-white transition-colors"
        >
          <X className="h-4 w-4" />
        </button>
      </div>

      <div className="flex-1 overflow-auto bg-black/5 min-h-0">
        {aiOutput ? (
          // ... AI logic same ...
          <div className="p-8 max-w-4xl animate-in fade-in duration-500 text-left">
            <div className="flex items-center gap-3 mb-6">
              <div className="p-2 rounded-lg bg-primary/10 border border-primary/20">
                {aiMode === "explain" ? (
                  <HelpCircle className="h-5 w-5 text-primary" />
                ) : (
                  <Lightbulb className="h-5 w-5 text-primary" />
                )}
              </div>
              <div>
                <h3 className="text-zinc-200 font-bold text-xs uppercase tracking-widest">
                  {aiMode === "explain"
                    ? "Query Intelligence Report"
                    : "Optimization Suggestions"}
                </h3>
                <p className="text-[9px] text-zinc-500 uppercase font-black tracking-tighter">
                  Generated by GPT-4o Agent
                </p>
              </div>
              <button
                onClick={onCloseAiOutput}
                className="ml-auto text-[10px] font-black text-zinc-500 hover:text-white uppercase tracking-widest flex items-center gap-2"
              >
                <X className="h-4 w-4" />
                Close
              </button>
            </div>
            <div className="prose prose-invert prose-sm max-w-none text-zinc-400 leading-relaxed font-sans whitespace-pre-wrap selection:bg-primary/20">
              {aiOutput}
            </div>
            {aiMode === "optimize" && (
              <div className="mt-8 flex items-center gap-4 p-4 rounded-xl border border-white/5 bg-white/[0.02]">
                <Zap className="h-4 w-4 text-primary" />
                <span className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest">
                  Apply these changes to see significant performance gains.
                </span>
              </div>
            )}
          </div>
        ) : bottomTab === "results" ? (
          isRunning ? (
            <div className="h-full flex flex-col items-center justify-center p-12 text-center">
              <div className="relative mb-8">
                <Loader2 className="h-12 w-12 text-primary animate-spin" />
                <div className="absolute inset-0 bg-primary/20 blur-2xl animate-pulse"></div>
              </div>
              <h3 className="text-sm font-black text-white uppercase tracking-[0.3em] mb-2 animate-pulse">
                Processing Query
              </h3>
              <p className="text-[9px] text-zinc-600 font-black uppercase tracking-widest">
                Awaiting response from high-performance engine...
              </p>
            </div>
          ) : Array.isArray(queryResults) && queryResults.length > 0 ? (
            <div className="overflow-x-auto w-full scrollbar-hide">
              <table className="w-full text-left border-collapse text-[11px] min-w-[600px]">
                <thead className="sticky top-0 bg-zinc-900 z-10 shadow-sm">
                  <tr>
                    {Object.keys(queryResults[0]).map((key) => (
                      <th
                        key={key}
                        className="px-4 py-2 font-bold text-zinc-500 border-b border-white/5 whitespace-nowrap"
                      >
                        {key}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {queryHistory.length > 0 &&
                    queryResults.map((row, i) => (
                      <tr
                        key={i}
                        className="border-b border-white/[0.02] hover:bg-white/[0.02] transition-colors"
                      >
                        {Object.values(row).map((val, j) => (
                          <td
                            key={j}
                            className="px-4 py-2 font-mono text-zinc-400 truncate max-w-[300px]"
                          >
                            {val === null ? (
                              <span className="font-italic text-zinc-600">
                                NULL
                              </span>
                            ) : (
                              String(val)
                            )}
                          </td>
                        ))}
                      </tr>
                    ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="h-full flex flex-col items-center justify-center text-zinc-600 p-12 text-center opacity-40">
              <Terminal className="h-10 w-10 mb-4 opacity-20" />
              <h4 className="text-[10px] font-black uppercase tracking-[0.2em]">
                No results to display
              </h4>
              <p className="text-[9px] font-bold uppercase mt-2">
                Buffer is empty for this command
              </p>
            </div>
          )
        ) : (
          /* History Tab View */
          <div className="flex flex-col h-full">
            {isLoadingHistory ? (
              <div className="flex-1 flex flex-col items-center justify-center gap-4 text-zinc-500">
                <Loader2 className="h-6 w-6 animate-spin text-primary" />
                <span className="text-[10px] font-black uppercase tracking-widest">
                  Retrieving audit logs...
                </span>
              </div>
            ) : queryHistory.length > 0 ? (
              <div className="overflow-x-auto w-full scrollbar-hide">
                <table className="w-full text-left border-collapse text-[11px] min-w-[700px]">
                  <thead className="sticky top-0 bg-zinc-900 z-10 shadow-sm">
                    <tr>
                      <th className="px-4 lg:px-6 py-3 font-bold text-zinc-500 border-b border-white/5 w-16 uppercase tracking-tighter text-[9px]">
                        Status
                      </th>
                      <th className="px-4 lg:px-6 py-3 font-bold text-zinc-500 border-b border-white/5 uppercase tracking-tighter text-[9px]">
                        SQL Query
                      </th>
                      <th className="px-4 lg:px-6 py-3 font-bold text-zinc-500 border-b border-white/5 w-24 uppercase tracking-tighter text-[9px]">
                        Duration
                      </th>
                      <th className="px-4 lg:px-6 py-3 font-bold text-zinc-500 border-b border-white/5 w-40 uppercase tracking-tighter text-[9px]">
                        Timestamp
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {queryHistory.map((log) => (
                      <tr
                        key={log.id}
                        className="border-b border-white/[0.02] hover:bg-white/[0.04] transition-colors cursor-pointer group/row text-left"
                        onClick={() => onRestoreQuery(log.query)}
                      >
                        <td className="px-4 lg:px-6 py-3">
                          {log.success ? (
                            <CheckCircle2 className="h-4 w-4 text-primary" />
                          ) : (
                            <AlertCircle className="h-4 w-4 text-red-500" />
                          )}
                        </td>
                        <td className="px-4 lg:px-6 py-3 font-mono text-zinc-300">
                          <div className="truncate max-w-[200px] sm:max-w-md lg:max-w-[500px]">
                            {log.query}
                          </div>
                        </td>
                        <td className="px-4 lg:px-6 py-3 font-mono text-zinc-500 text-[10px]">
                          {log.executionTimeMs}ms
                        </td>
                        <td className="px-4 lg:px-6 py-3 text-zinc-600 text-[10px] whitespace-nowrap">
                          {new Date(log.createdAt).toLocaleString()}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center text-zinc-600 p-10 text-center gap-4">
                <HistoryIcon className="h-10 w-10 opacity-20" />
                <div className="max-w-xs">
                  <h3 className="text-zinc-400 font-bold text-[11px] uppercase tracking-widest mb-1">
                    No History Yet
                  </h3>
                  <p className="text-[10px] uppercase tracking-wider leading-relaxed opacity-60">
                    Queries you run will appear here. You can click any entry to
                    restore the SQL to the editor.
                  </p>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default QueryResultsArea;
