import React from "react";
import { Terminal, History as HistoryIcon, X, HelpCircle, Lightbulb, Zap, CheckCircle2, AlertCircle, Loader2 } from "lucide-react";

interface QueryResultsAreaProps {
    queryResults: any[] | null;
    bottomTab: "results" | "history";
    onSetTab: (tab: "results" | "history") => void;
    onClose: () => void;
    aiOutput: string | null;
    onCloseAiOutput: () => void;
    aiMode: string;
    isLoadingHistory: boolean;
    queryHistory: any[];
    onRestoreQuery: (query: string) => void;
}

const QueryResultsArea = ({
    queryResults,
    bottomTab,
    onSetTab,
    onClose,
    aiOutput,
    onCloseAiOutput,
    aiMode,
    isLoadingHistory,
    queryHistory,
    onRestoreQuery
}: QueryResultsAreaProps) => {
    if (!queryResults && bottomTab !== "history") return null;

    return (
        <div className="flex-1 flex flex-col bg-[#021016]/50 overflow-hidden border-t border-white/5 min-h-0 animate-in slide-in-from-bottom duration-500">
            <div className="flex items-center justify-between px-6 py-2 border-b border-white/5 bg-black/20 shrink-0">
                <div className="flex items-center gap-6">
                    <button 
                        onClick={() => onSetTab("results")}
                        className={`flex items-center gap-3 py-1 transition-all relative ${bottomTab === "results" ? 'text-primary' : 'text-zinc-500 hover:text-zinc-300'}`}
                    >
                        <Terminal className="h-3.5 w-3.5" />
                        <span className="text-[10px] font-black uppercase tracking-widest">Query Output</span>
                        {bottomTab === "results" && <div className="absolute -bottom-[9px] left-0 right-0 h-0.5 bg-primary shadow-[0_0_8px_rgba(0,237,100,0.5)]" />}
                    </button>
                    <button 
                        onClick={() => onSetTab("history")}
                        className={`flex items-center gap-3 py-1 transition-all relative ${bottomTab === "history" ? 'text-primary' : 'text-zinc-500 hover:text-zinc-300'}`}
                    >
                        <HistoryIcon className="h-3.5 w-3.5" />
                        <span className="text-[10px] font-black uppercase tracking-widest">History</span>
                        {bottomTab === "history" && <div className="absolute -bottom-[9px] left-0 right-0 h-0.5 bg-primary shadow-[0_0_8px_rgba(0,237,100,0.5)]" />}
                    </button>
                </div>
                <button 
                    onClick={onClose}
                    className="p-1 hover:text-white text-zinc-600 transition-colors"
                >
                    <X className="h-4 w-4" />
                </button>
            </div>
            
            <div className="flex-1 overflow-auto bg-black/5 min-h-0">
                {aiOutput ? (
                    <div className="p-8 max-w-4xl animate-in fade-in duration-500 text-left">
                        <div className="flex items-center gap-3 mb-6">
                            <div className="p-2 rounded-lg bg-primary/10 border border-primary/20">
                                {aiMode === "explain" ? <HelpCircle className="h-5 w-5 text-primary" /> : <Lightbulb className="h-5 w-5 text-primary" />}
                            </div>
                            <div>
                                <h3 className="text-zinc-200 font-bold text-xs uppercase tracking-widest">
                                    {aiMode === "explain" ? "Query Intelligence Report" : "Optimization Suggestions"}
                                </h3>
                                <p className="text-[9px] text-zinc-500 uppercase font-black tracking-tighter">Generated by GPT-4o Agent</p>
                            </div>
                            <button 
                                onClick={onCloseAiOutput}
                                className="ml-auto text-[10px] font-black text-zinc-500 hover:text-white uppercase tracking-widest flex items-center gap-2"
                            >
                                <X className="h-4 w-4" />
                                Close
                            </button>
                        </div>
                        <div className="prose prose-invert prose-sm max-w-none text-zinc-400 leading-relaxed font-sans whitespace-pre-wrap selection:bg-primary/20">
                            {aiOutput}
                        </div>
                        {aiMode === "optimize" && (
                            <div className="mt-8 flex items-center gap-4 p-4 rounded-xl border border-white/5 bg-white/[0.02]">
                                <Zap className="h-4 w-4 text-primary" />
                                <span className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest">Apply these changes to see significant performance gains.</span>
                            </div>
                        )}
                    </div>
                ) : bottomTab === "results" ? (
                    Array.isArray(queryResults) && queryResults.length > 0 ? (
                        <table className="w-full text-left border-collapse text-[11px]">
                            <thead className="sticky top-0 bg-zinc-900 z-10 shadow-sm">
                                <tr>
                                    {Object.keys(queryResults[0]).map((key) => (
                                        <th key={key} className="px-4 py-2 font-bold text-zinc-500 border-b border-white/5">{key}</th>
                                    ))}
                                </tr>
                            </thead>
                            <tbody>
                                {queryResults.map((row, i) => (
                                    <tr key={i} className="border-b border-white/[0.02] hover:bg-white/[0.02] transition-colors">
                                        {Object.values(row).map((val: any, j) => (
                                            <td key={j} className="px-4 py-2 font-mono text-zinc-400 truncate max-w-[300px]">
                                                {val === null ? <span className="font-italic text-zinc-600">NULL</span> : String(val)}
                                            </td>
                                        ))}
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    ) : queryResults ? (
                        <div className="h-full flex flex-col items-center justify-center p-10 text-center">
                            <div className="p-8 rounded-2xl bg-white/[0.02] border border-white/5 max-w-md">
                                <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-4">
                                    <Terminal className="h-5 w-5 text-primary" />
                                </div>
                                <h3 className="text-zinc-200 font-bold text-sm mb-2 uppercase tracking-widest text-[11px]">Query Executed Successfully</h3>
                                <p className="text-zinc-500 text-[10px] uppercase tracking-wider leading-relaxed">
                                    {Array.isArray(queryResults) 
                                        ? "The statement returned 0 rows. Your schema might be empty or the filter didn't match any data." 
                                        : "The query was processed by the engine without returning a dataset. (Affected rows: " + ((queryResults as any).rowCount || (queryResults as any).affectedRows || 0) + ")"
                                    }
                                </p>
                                {!Array.isArray(queryResults) && (
                                    <pre className="mt-4 p-4 rounded bg-black/40 text-[10px] text-zinc-400 font-mono text-left overflow-auto max-h-[200px]">
                                        {JSON.stringify(queryResults, null, 2)}
                                    </pre>
                                )}
                            </div>
                        </div>
                    ) : (
                        <div className="h-full flex flex-col items-center justify-center text-zinc-600 font-mono text-[10px] uppercase tracking-widest gap-4">
                            <Loader2 className="h-5 w-5 animate-spin" />
                            No output to display. Run a query first.
                        </div>
                    )
                ) : (
                    /* History Tab View */
                    <div className="flex flex-col h-full">
                        {isLoadingHistory ? (
                            <div className="flex-1 flex flex-col items-center justify-center gap-4 text-zinc-500">
                                <Loader2 className="h-6 w-6 animate-spin text-primary" />
                                <span className="text-[10px] font-black uppercase tracking-widest">Retrieving audit logs...</span>
                            </div>
                        ) : queryHistory.length > 0 ? (
                            <table className="w-full text-left border-collapse text-[11px]">
                                <thead className="sticky top-0 bg-zinc-900 z-10 shadow-sm">
                                    <tr>
                                        <th className="px-6 py-3 font-bold text-zinc-500 border-b border-white/5 w-16 uppercase tracking-tighter text-[9px]">Status</th>
                                        <th className="px-6 py-3 font-bold text-zinc-500 border-b border-white/5 uppercase tracking-tighter text-[9px]">SQL Query</th>
                                        <th className="px-6 py-3 font-bold text-zinc-500 border-b border-white/5 w-24 uppercase tracking-tighter text-[9px]">Duration</th>
                                        <th className="px-6 py-3 font-bold text-zinc-500 border-b border-white/5 w-40 uppercase tracking-tighter text-[9px]">Timestamp</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {queryHistory.map((log) => (
                                        <tr 
                                            key={log.id} 
                                            className="border-b border-white/[0.02] hover:bg-white/[0.04] transition-colors cursor-pointer group/row text-left"
                                            onClick={() => onRestoreQuery(log.query)}
                                        >
                                            <td className="px-6 py-3">
                                                {log.success ? (
                                                    <CheckCircle2 className="h-4 w-4 text-primary" />
                                                ) : (
                                                    <AlertCircle className="h-4 w-4 text-red-500" />
                                                )}
                                            </td>
                                            <td className="px-6 py-3 font-mono text-zinc-300">
                                                <div className="truncate max-w-[500px]">{log.query}</div>
                                            </td>
                                            <td className="px-6 py-3 font-mono text-zinc-500 text-[10px]">
                                                {log.executionTimeMs}ms
                                            </td>
                                            <td className="px-6 py-3 text-zinc-600 text-[10px] whitespace-nowrap">
                                                {new Date(log.createdAt).toLocaleString()}
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        ) : (
                            <div className="flex-1 flex flex-col items-center justify-center text-zinc-600 p-10 text-center gap-4">
                                <HistoryIcon className="h-10 w-10 opacity-20" />
                                <div className="max-w-xs">
                                    <h3 className="text-zinc-400 font-bold text-[11px] uppercase tracking-widest mb-1">No History Yet</h3>
                                    <p className="text-[10px] uppercase tracking-wider leading-relaxed opacity-60">
                                        Queries you run will appear here. You can click any entry to restore the SQL to the editor.
                                    </p>
                                </div>
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
};

export default QueryResultsArea;
